// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// Estilos de bootstrap
import 'bootstrap/dist/css/bootstrap.min.css';
import BootstrapClient from '@/components/Bootstrap/BootstrapClient';

import Cabecera from '@/components/Layout/Header/Header'
import Footer from '@/components/Layout/Footer/Footer';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <BootstrapClient/>

        <Cabecera/>
        {children}

        <Footer/>
      </body>
    </html>
  );
}
